baseURL = "https://www.florian.fyi/"
languageCode = "en-us"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1 
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2 
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3 
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4


